//// Login a user
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "dgim",
    "password": "UpperLower8!"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "demo",
    "password": "UpperLower8!"
}

