// Get all projects
GET http://localhost:3001/api/projects

###

// Add a project
POST http://localhost:3001/api/projects
Content-Type: application/json

{
    "projectNo": 2,
    "title": "Second Project",
    "description": "This is my second project",
    "tech_stacks": "javascript",
    "demoUrl": "http://demo.com",
    "githubUrl": "http://github.com",
    "imageUrl": "images should be stored as url",
    "important": true
}
