//// Get all techs
GET http://localhost:3001/api/techs

###

//// Add a tech
POST http://localhost:3001/api/techs
Content-Type: application/json

{
    "name": "React",
    "icon": "SiReact"
}

### 

//// Add a tech
POST http://localhost:3001/api/techs
Content-Type: application/json

{
    "name": "JavaScript",
    "icon": "SiJavascript"
}

###

//// Delete a tech
DELETE http://localhost:3001/api/techs/687c3f65815046710dbc9bc6
Content-Type: application/json

### 

//// Delete all