//// Get all techs
GET http://localhost:3001/api/techs

###

//// Add a tech
POST http://localhost:3001/api/techs
Content-Type: application/json

{
    "name": "React",
    "icon": "React",
    "level": "novice"
}

### 

//// Add a tech
POST http://localhost:3001/api/techs
Content-Type: application/json

{
    "name": "JavaScript",
    "icon": "Javascript",
    "level": "novice"
}

###

//// Delete a tech
DELETE http://localhost:3001/api/techs/6887b7d0f8efba52dcc6d1f8
Content-Type: application/json

### 

//// Delete all